Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data"
        testsets: ['highway_test']
        transform_list:
            resize: 
                size: [352, 576]
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/HighwayLane"
